/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import LetoBannerDemo from "./ui/LetoBannerDemo"
import LetoCoinDemo from "./ui/LetoCoinDemo"
import LetoExtendedDemo from "./ui/LetoExtendedDemo"
import LetoFeedDemo from "./ui/LetoFeedDemo"
import LetoInterstitialDemo from "./ui/LetoInterstitialDemo"
import LetoMainDemo from "./ui/LetoMainDemo"
import LetoRedPackDemo from "./ui/LetoRedPackDemo"
import LetoRewardedVideoDemo from "./ui/LetoRewardedVideoDemo"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("ui/LetoBannerDemo.js",LetoBannerDemo);
		reg("ui/LetoCoinDemo.js",LetoCoinDemo);
		reg("ui/LetoExtendedDemo.js",LetoExtendedDemo);
		reg("ui/LetoFeedDemo.js",LetoFeedDemo);
		reg("ui/LetoInterstitialDemo.js",LetoInterstitialDemo);
		reg("ui/LetoMainDemo.js",LetoMainDemo);
		reg("ui/LetoRedPackDemo.js",LetoRedPackDemo);
		reg("ui/LetoRewardedVideoDemo.js",LetoRewardedVideoDemo);
    }
}
GameConfig.width = 640;
GameConfig.height = 1136;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "test/LetoMainDemo.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
